"""empty message

Revision ID: b64c03de2cc5
Revises: 79cebe296ee2
Create Date: 2018-04-23 23:26:01.821818

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b64c03de2cc5'
down_revision = '79cebe296ee2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message_field',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('field_name', sa.Text(), nullable=True),
    sa.Column('field_data', sa.Text(), nullable=True),
    sa.Column('message_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['message.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('message_fields')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message_fields',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('field_name', sa.TEXT(), nullable=True),
    sa.Column('field_data', sa.TEXT(), nullable=True),
    sa.Column('message_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['message.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('message_field')
    # ### end Alembic commands ###
